import './globals.css'
import { Lato } from 'next/font/google'


const lato = Lato({
  weight: ["100", "300", "400", "700","900"],
  subsets: ["latin"],
});

export const metadata = {
  title: 'Formik-Nextjs ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
